version: 2
jobs:
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/golang:1.15
    parallelism: 2
    environment:
      TEST_RESULTS: /tmp/test-results
      KUBE_BUILDER_VERSION: 2.3.1
      KUBE_BUILDER_ARCH: amd64
    steps:
      - checkout
      - run:
          name: Install kubebuilder
          command: |
            curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${KUBE_BUILDER_VERSION}/kubebuilder_${KUBE_BUILDER_VERSION}_linux_${KUBE_BUILDER_ARCH}.tar.gz
            tar -zxvf kubebuilder_${KUBE_BUILDER_VERSION}_linux_${KUBE_BUILDER_ARCH}.tar.gz
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run unit tests
          command: |
            export KUBEBUILDER_ASSETS=$(pwd)/kubebuilder_${KUBE_BUILDER_VERSION}_linux_${KUBE_BUILDER_ARCH}/bin
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml
      - run: make
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
