# permissions for end users to edit objecttemplateparams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: objecttemplateparams-editor-role
rules:
- apiGroups:
  - template.ericogr.github.com
  resources:
  - objecttemplateparams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - template.ericogr.github.com
  resources:
  - objecttemplateparams/status
  verbs:
  - get
