# permissions for end users to view objecttemplateparams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: objecttemplateparams-viewer-role
rules:
- apiGroups:
  - template.k8s.ericogr.com.br
  resources:
  - objecttemplateparams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - template.k8s.ericogr.com.br
  resources:
  - objecttemplateparams/status
  verbs:
  - get
