# permissions for end users to view objecttemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: objecttemplate-viewer-role
rules:
- apiGroups:
  - template.totvs.app.github.com
  resources:
  - objecttemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - template.totvs.app.github.com
  resources:
  - objecttemplates/status
  verbs:
  - get
