
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - template.totvs.app.github.com
  resources:
  - aocparams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - template.totvs.app.github.com
  resources:
  - aocparams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - template.totvs.app.github.com
  resources:
  - autoobjectcreations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - template.totvs.app.github.com
  resources:
  - autoobjectcreations/status
  verbs:
  - get
  - patch
  - update
