---
apiVersion: template.ericogr.github.com/v1
kind: ObjectTemplate
metadata:
  name: objecttemplate-configmap-test
spec:
  description: ConfigMap test
  objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      labels:
        chave1: valor1
        chave2: valor2
      annotations:
        chave1a: valor1a
        chave2a: valor2a
    name: configmap-test
    templateBody: |-
      data:
        name: '{{ .name }}'
        age: '{{ .age }}'